export const cinemaLinks = {
  "CineStar Zagreb": "https://www.blitz-cinestar.hr/cinestar-zagreb",
  "CineStar Zagreb (Branimir centar)": "https://www.blitz-cinestar.hr/cinestar-zagreb",
  "CineStar Novi Zagreb (Avenue mall)": "https://www.blitz-cinestar.hr/cinestar-novi-zagreb",
  "CineStar Arena IMAX (Arena centar)": "https://www.blitz-cinestar.hr/cinestar-arena-imax",
  "CineStar Joker Split": "https://www.blitz-cinestar.hr/cinestar-joker-split",
  "CineStar 4DX Mall of Split ": "https://www.blitz-cinestar.hr/cinestar-4dx-mall-of-split",
  "CineStar Rijeka 4DX (Tower Center)": "https://www.blitz-cinestar.hr/cinestar-rijeka-4dx",
  "CineStar Zadar (City Galleria)": "https://www.blitz-cinestar.hr/cinestar-zadar",
  "CineStar Šibenik (Dalmare centar)": "https://www.blitz-cinestar.hr/cinestar-sibenik",
  "CineStar Osijek (Portanova centar)": "https://www.blitz-cinestar.hr/cinestar-osijek",
  "CineStar Varaždin (Lumini centar)  ": "https://www.blitz-cinestar.hr/cinestar-varazdin",
  "CineStar Dubrovnik (Dvori Lapad)   ": "https://www.blitz-cinestar.hr/cinestar-dubrovnik",
  "CineStar Sl. Brod (City Colosseum)     ": "https://www.blitz-cinestar.hr/cinestar-slavonski-brod",
  "CineStar Vukovar (K Centar Golubica)   ": "https://www.blitz-cinestar.hr/cinestar-vukovar",
  "CineStar Mostar (Mepas Mall)   ": "https://www.blitz-cinestar-bh.ba/cinestar-mostar",
  "CineStar Bihać (Bingo centar)   ": "https://www.blitz-cinestar-bh.ba/cinestar-bihac",
  "CineStar Tuzla (Bingo City Center)": "https://www.blitz-cinestar-bh.ba/cinestar-tuzla",
}
